### ISSUE TITLE
Node-Red crashes if copy/paste nodes.

### ISSUE THREAD

**Issue by Supergiovane** [marcus-j-davies/node-red-contrib-homekit-preconfigured#3]
Hi Marcus,
if i copy/paste a node, node-red crashes because some properties are duplicated as well.

13 Feb 13:56:02 - Error: listen EADDRINUSE: address already in use :::42497
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at EventedHTTPServer._this.listen (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:86:30)
    at HAPServer._this.listen (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/node_modules/hap-nodejs/dist/lib/HAPServer.js:191:31)
    at Accessory._this.publish (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/node_modules/hap-nodejs/dist/lib/Accessory.js:558:27)
    at new Init (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/hk-garage-door/hk-garage-door.js:183:19)
    at Object.createNode (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
    at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:189:48)
    at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at tryCatchReject (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by marcus-j-davies** [comment]
Good spot!

It should be quite a simple fix.
This is the only drawback in using a non bridged approach guess.

Dragging in a new node is a temporary measure in the mean time.
I'll look to see if there are any  'node paste' events, that i can use to regenerate new values.

**Comment by Supergiovane** [comment]
No problem for me. I manyally changed the properties and restarted node-red.
I'ts near impossible to change the .html properties from inside the .js code.
You should eventually proceed by 
warning the user about the error, in the node's status; 
disabling the affected node; 
allow the user to "regenerate" the properties by adding a button in the html config.
That's much simpler.
;-)

**Comment by marcus-j-davies** [comment]
Yup,

After reading what is available = No events from what i can see.
I'm going to wrap the HAP Publish block in a try/catch (should have done that anyway)
And react accordingly as you have suggested.

I assume other than this hick up, the new node is working? with the correct icons etc?

**Comment by Supergiovane** [comment]
Yes this is working flawlessy. Many thanks!!!

**Comment by Supergiovane** [comment]
Just a little update...
Even if the hk-nodes are correctly configured, up and running, if you deploy a flow with "Full Deploy" button in node-red, node-red crashes with the same error.

> 4 Feb 14:10:38 - Error: listen EADDRINUSE: address already in use :::55164
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at Server.listen (net.js:1437:7)
    at EventedHTTPServer._this.listen (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:86:30)
    at HAPServer._this.listen (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/node_modules/hap-nodejs/dist/lib/HAPServer.js:191:31)
    at Accessory._this.publish (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/node_modules/hap-nodejs/dist/lib/Accessory.js:558:27)
    at new Init (/home/pi/.node-red/node_modules/node-red-contrib-homekit-preconfigured/hk-alarm/hk-alarm.js:166:19)
    at Object.createNode (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
    at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:189:48)
    at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21

**Comment by marcus-j-davies** [comment]
Thanks Supergiovane.

I 'Unpublish' the HAP object on the node 'close' event.
it looks as if I am not clearing it all up after. 

The HAP Unpublish method, may not be enough, to issue a complete disposal of the HAP objects.
I'll get it fixed at the same time. - should be able to get it sorted this weekend.

**Comment by Supergiovane** [comment]
Thanks.
You can take a look at how the homekit bridged version cleans the matter at flow redeployment.
Other than that, no issues at all.
Buon San Valentino

**Comment by marcus-j-davies** [comment]
Yup,

A little more occurs than just a simple 'Unpublish', so will take a look this evening, and adopt the same behavior.

**Comment by marcus-j-davies** [comment]
Do you mind testing something for me, if convenient?

Changing this:
```
 node.on('close', function ()
        {
            accessory.unpublish();
        });
```

to this.
```
 node.on('close', function (done)
        {
            accessory.destroy();
            done();
        });
```

the HAP object has a method called destroy, which does most of the heavy lifting.
you can also pass in a callback to the on event, which i believe, instructs Node Red to wait.

This will be per hk-node. so, again if its not to inconvenient?

this is to fix the full deploy issue

**Comment by Supergiovane** [comment]
Ok, i'll do it immediately. Please hold on.

**Comment by Supergiovane** [comment]
Hi Marcus.
It works. I tested only on hk-switch, but should go for all other nodes as well.

**Comment by marcus-j-davies** [comment]
Nice!

I'll include that fix (along with the duplication error) this evening.

Thank you, for all of this.

**Comment by Supergiovane** [comment]
No problems, thank you to you instead.

**Comment by marcus-j-davies** [comment]
Ok....These are fixed.

After reviewing the source  for Hap-NodeJS, I am not able to catch HAPServer object errors (responsible for the listening on the specified port) either that, or i'm simply not clever enough.
Attempting to try/catch on the Publish method (which opens up the port) , it doesn't catch.

So... each node now records its ID in a config named 'originalId', this is recorded on 'oneditsaved'
this originalId value is checked on the init of the node with its actual id and if it differs it does not load with a warning message. - only saving the config will the 2 match.

for current set ups (like yours) - just opening/saving the config will (providing it is unique values) allow you to continue as normal. when you copy and paste, the originalId  will remain but be set to the ID of the source node - only reviewing the config will it re-adjust.

> "Please review the Configuration, to ensure this node's values (username,pin & port) are unique across your homekit devices. If you simply open and save the configuration without making any necessary changes. you risk bigger problems."

Sneaky I know - but it works.

I haven't been developing with NodeJS/NR all that long (I'm a full time .Net developer).
so any recommendations on things like this - always welcome (I'm also fairy new on github)

Close if all good and well.

**Comment by Supergiovane** [comment]
Thank you Marcus. 
I too come from .net ;-)
Tomorrow i’ll try. 
Thank you for your support. 
Good night!
